using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Versionable.Analyzers.Grammar;

namespace Versionable.Analyzers;

/// <summary>
/// Emits per-type <c>VersionableMetadata</c>, typed field accessors, a constructor invoker,
/// and a <c>[ModuleInitializer]</c> registry registration for every <c>[Versionable]</c> type.
/// </summary>
/// <remarks>
/// Replaces Python's runtime reflection (<c>_resolveFields</c> /
/// <c>typing.get_type_hints</c> in <c>src/versionable/_base.py</c>) with compile-time
/// codegen, which is what keeps the runtime Native AOT and trimming safe (ADR-0003).
/// <para>
/// The generator reports no diagnostics of its own: every reason it can decline to generate
/// — a non-partial type, an unrenderable field, no usable constructor — is reported by
/// <see cref="SchemaHashAnalyzer"/> from the same <see cref="SchemaModel"/>, so a message is
/// never emitted twice and never depends on which of the two ran.
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class VersionableMetadataGenerator : IIncrementalGenerator
{
    internal const string Runtime = "global::Versionable.";

    private static readonly SymbolDisplayFormat _clrTypeFormat = SymbolDisplayFormat.FullyQualifiedFormat;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // A marker stamping every compilation the generator actually ran in, so the pipeline
        // is provably wired rather than merely referenced. An assembly attribute rather than a
        // type, so the same marker landing in two assemblies that see each other's internals
        // cannot collide (CS0433).
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource(
            "VersionableGeneratorMarker.g.cs",
            """
            // <auto-generated/>
            [assembly: System.Reflection.AssemblyMetadata("Versionable.Generator", "VersionableMetadataGenerator")]
            """));

        IncrementalValuesProvider<(string HintName, string Text)?> sources = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                SchemaModelBuilder.VersionableAttributeName,
                static (node, _) => node is TypeDeclarationSyntax,
                static (attributeContext, _) => Emit(attributeContext));

        context.RegisterSourceOutput(sources, static (production, source) =>
        {
            if (source is { } emitted)
            {
                production.AddSource(emitted.HintName, emitted.Text);
            }
        });
    }

    private static (string HintName, string Text)? Emit(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol type || context.Attributes.Length == 0)
        {
            return null;
        }

        SchemaModel model = SchemaModelBuilder.Build(type, context.Attributes[0]);
        if (!model.CanGenerate)
        {
            return null;
        }

        return (HintName(type), Render(model));
    }

    private static string HintName(INamedTypeSymbol type)
    {
        StringBuilder name = new(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        name.Replace("global::", string.Empty);
        foreach (char invalid in new[] { '<', '>', ',', ' ', '+', ':' })
        {
            name.Replace(invalid, '_');
        }

        return name + ".Versionable.g.cs";
    }

    private static string Render(SchemaModel model)
    {
        Writer writer = new();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        List<INamedTypeSymbol> nesting = new();
        for (INamedTypeSymbol? current = model.Type; current is not null; current = current.ContainingType)
        {
            nesting.Insert(0, current);
        }

        bool hasNamespace = model.Type.ContainingNamespace is { IsGlobalNamespace: false };
        if (hasNamespace)
        {
            writer.Line($"namespace {model.Type.ContainingNamespace.ToDisplayString()}");
            writer.Open();
        }

        for (int i = 0; i < nesting.Count - 1; i++)
        {
            writer.Line($"{Declaration(nesting[i])}");
            writer.Open();
        }

        writer.Line($"{Declaration(model.Type)} : {Runtime}IVersionableMetadataProvider");
        writer.Open();
        RenderBody(writer, model);
        writer.Close();

        for (int i = 0; i < nesting.Count - 1; i++)
        {
            writer.Close();
        }

        if (hasNamespace)
        {
            writer.Close();
        }

        return writer.ToString();
    }

    private static void RenderBody(Writer writer, SchemaModel model)
    {
        string self = model.Type.ToDisplayString(_clrTypeFormat);

        // A [Versionable] type deriving from another one — the polymorphic base GRAMMAR §9
        // blesses — declares members that hide the base's. Each type needs its own metadata, so
        // hiding is exactly what is intended; saying so is what keeps CS0108 from failing the
        // consumer's build under TreatWarningsAsErrors.
        string hide = model.HidesBaseMembers ? "new " : string.Empty;

        writer.Line("/// <summary>Generated schema metadata for this type. The same instance on every call.</summary>");
        writer.Line(
            $"public static {hide}{Runtime}VersionableMetadata VersionableMetadata => _versionableMetadata;");
        writer.Line();
        writer.Line($"private static readonly {Runtime}VersionableMetadata _versionableMetadata = new()");
        writer.Open();
        writer.Line($"ClrType = typeof({self}),");
        writer.Line($"Name = {Quote(model.SerializationName)},");
        writer.Line($"Version = {model.Version.ToString(CultureInfo.InvariantCulture)},");
        writer.Line($"Hash = {Quote(model.DeclaredHash.Length == 0 ? model.ComputedHash : model.DeclaredHash)},");
        writer.Line($"Unknown = {Runtime}UnknownFieldPolicy.{model.UnknownPolicy},");
        writer.Line($"SkipDefaults = {Bool(model.SkipDefaults)},");
        writer.Line($"ValidateLiterals = {Bool(model.ValidateLiterals)},");

        if (model.OldNames.Length > 0)
        {
            writer.Line($"OldNames = new string[] {{ {string.Join(", ", model.OldNames.Select(Quote))} }},");
        }

        writer.Line($"Fields = new {Runtime}FieldDescriptor[]");
        writer.Open();
        foreach (SchemaField field in model.Fields)
        {
            RenderField(writer, field, self);
        }

        writer.CloseWith("},");

        writer.Line($"Factory = static values => {FactoryExpression(model, self)},");

        RenderMigrations(writer, model, self);

        writer.CloseWith("};");

        if (model.SupportsModuleInitializer)
        {
            writer.Line();
            RenderRegistration(writer, model, self, hide);
        }
    }

    /// <summary>
    /// Emits <c>VersionableMetadata.Migrations</c> from whichever of the two declaration forms the
    /// type used.
    /// </summary>
    /// <remarks>
    /// A nested <c>Migrate</c> that is itself an <c>IMigrationChain</c> is handed over as-is; that
    /// is the escape hatch for a chain decided at run time. Otherwise the members of the nested
    /// <c>Migrate</c> class — <c>V1</c>/<c>V2</c> builders and <c>[Migration]</c> methods — are
    /// composed into one <c>MigrationChain</c> here, at compile time, which is what Python's
    /// <c>resolveMigrations</c> does by walking <c>dir(Migrate)</c> on every load.
    /// <para>
    /// The two forms are checked in that order rather than assumed disjoint: a <c>Migrate</c> that
    /// implements the interface may also hold builder members, and the interface is the more
    /// explicit statement of intent.
    /// </para>
    /// </remarks>
    private static void RenderMigrations(Writer writer, SchemaModel model, string self)
    {
        string migrate = $"{self}.{SchemaModelBuilder.MigrateClassName}";

        if (model.MigrateTypeIsChain)
        {
            writer.Line($"Migrations = new {migrate}(),");
            return;
        }

        if (model.Migrations.Length == 0)
        {
            return;
        }

        writer.Line($"Migrations = new {Runtime}Migrations.MigrationChain(");
        writer.Indent();
        for (int i = 0; i < model.Migrations.Length; i++)
        {
            SchemaMigration migration = model.Migrations[i];

            // The last step closes the constructor call, and the comma after it is the object
            // initializer's own separator.
            string separator = i == model.Migrations.Length - 1 ? ")," : ",";
            writer.Line(
                $"{Runtime}Migrations.MigrationStep.Of("
                    + $"{migration.FromVersion.ToString(CultureInfo.InvariantCulture)}, "
                    + $"{migrate}.{migration.MemberName}){separator}");
        }

        writer.Outdent();
    }

    private static void RenderField(Writer writer, SchemaField field, string self)
    {
        string clrType = field.ClrType.ToDisplayString(_clrTypeFormat);

        writer.Line($"new {Runtime}FieldDescriptor");
        writer.Open();
        writer.Line($"WireName = {Quote(field.WireName)},");
        writer.Line($"ClrName = {Quote(field.ClrName)},");
        writer.Line($"ClrType = typeof({clrType}),");
        writer.Line($"CanonicalType = {Quote(field.CanonicalType)},");
        writer.Line($"Getter = static instance => (({self})instance).{field.ClrName},");

        if (field.IsAssignable)
        {
            writer.Line(
                $"Setter = static (instance, value) => "
                + $"(({self})instance).{field.ClrName} = ({clrType})value!,");
        }

        if (field.DefaultExpression is not null)
        {
            // The cast carries the nullable annotation for a reference type, because
            // `Foo? Star { get; init; } = null;` is an ordinary declaration and `(Foo)(null)` is
            // CS8600 — an error under the TreatWarningsAsErrors this repo and its consumers use,
            // reported against generated source the author cannot edit. A field declared where
            // nullable is switched off gets the same treatment: the annotation is unknown there,
            // but the generated file is always `#nullable enable`, so a null default would trip
            // the same diagnostic.
            //
            // Value types keep their exact spelling. Widening `int` to `int?` here would turn
            // `= default` into null rather than 0, which the engine would then hand to the
            // factory as a missing value.
            bool castNullable = field.ClrType.IsReferenceType
                && field.ClrType.NullableAnnotation != NullableAnnotation.NotAnnotated;

            writer.Line("HasDefault = true,");
            writer.Line(
                $"DefaultFactory = static () => ({(castNullable ? FqNullable(field.ClrType) : clrType)})"
                + $"({field.DefaultExpression}),");
        }

        if (field.IsLiteral)
        {
            writer.Line(
                $"LiteralOptions = new object?[] {{ "
                + $"{string.Join(", ", field.LiteralValues.Select(CSharpLiteral))} }},");
            if (field.HasLiteralFallback)
            {
                writer.Line("HasLiteralFallback = true,");
                writer.Line($"LiteralFallback = {CSharpLiteral(field.LiteralFallback)},");
            }
        }

        RenderWireReader(writer, field);
        writer.CloseWith("},");
    }

    /// <summary>
    /// Emits the AOT materialization seam: a closed delegate that rebuilds this field's
    /// container, array, or tuple from the wire.
    /// </summary>
    /// <remarks>
    /// These are exactly the shapes <see cref="M:Versionable.Engine.WireValues.Read"/> refuses,
    /// and it refuses them for a reason: constructing a <c>List&lt;T&gt;</c> at runtime means
    /// <c>Activator.CreateInstance</c> over a type the trimmer cannot see (ADR-0003). The
    /// generator knows the type statically, so it writes the construction out and delegates
    /// every <em>element</em> back to the engine — <c>WireValues.Read</c> for scalars,
    /// converter types, and enums, <c>WireValues.ReadVersionable</c> for nested
    /// <c>[Versionable]</c> values, <c>AsList</c> / <c>AsMap</c> for the shape. Nesting
    /// recurses, so <c>Dictionary&lt;string, List&lt;Node&gt;&gt;</c> is one expression.
    /// <para>
    /// <c>WireValues.ReadUnion</c> is deliberately never emitted: C# spells optionality as
    /// <c>T?</c>, a two-member union that <see langword="null"/> short-circuits, and it has no
    /// type-level spelling for a union of three or more members. The same reason four
    /// conformance vectors are marked <c>csharpDeclarable: false</c>.
    /// </para>
    /// <para>
    /// There is no matching <c>WireWriter</c>. Lowering constructs nothing — the engine walks
    /// any collection generically on the runtime type — and enum wire mapping belongs to
    /// <c>EnumConverter</c>, which the engine's write path already routes through.
    /// </para>
    /// </remarks>
    private static void RenderWireReader(Writer writer, SchemaField field)
    {
        if (!NeedsReader(field.ClrType))
        {
            return;
        }

        writer.Line("WireReader = static wire =>");
        writer.Indent();
        writer.Line(ReadExpression(field.ClrType, "wire", 0) + ",");
        writer.Outdent();
    }

    /// <summary>
    /// Whether the engine needs a generated reader for <paramref name="type"/> — true exactly
    /// for the shapes <c>WireValues.Read</c> throws on.
    /// </summary>
    private static bool NeedsReader(ITypeSymbol type)
    {
        if (CanonicalTypeRenderer.TryUnwrapNullable(type, out ITypeSymbol inner))
        {
            return NeedsReader(inner);
        }

        if (type is IArrayTypeSymbol array)
        {
            // byte[] is the carve-out: BytesConverter owns it, as `bytes` rather than a list.
            return array.Rank == 1 && array.ElementType.SpecialType != SpecialType.System_Byte;
        }

        if (type is not INamedTypeSymbol named)
        {
            return false;
        }

        if (IsTuple(named))
        {
            return true;
        }

        return CanonicalTypeRenderer.FullName(named) switch
        {
            "System.Collections.Generic.List"
            or "System.Collections.Generic.HashSet"
            or "System.Collections.Frozen.FrozenSet"
            or "System.Collections.Immutable.ImmutableHashSet" => named.TypeArguments.Length == 1,
            "System.Collections.Generic.Dictionary" => named.TypeArguments.Length == 2,
            _ => false,
        };
    }

    private static bool IsTuple(INamedTypeSymbol named) =>
        named.IsTupleType
        || (CanonicalTypeRenderer.FullName(named) == "System.ValueTuple" && named.TypeArguments.Length > 0);

    /// <summary>
    /// A C# expression materializing <paramref name="wire"/> into <paramref name="type"/>.
    /// </summary>
    /// <param name="type">The declared type to produce.</param>
    /// <param name="wire">An expression of static type <c>object?</c>.</param>
    /// <param name="depth">Nesting depth, which keeps lambda parameter names unique.</param>
    /// <returns>An expression whose static type is <paramref name="type"/>.</returns>
    private static string ReadExpression(ITypeSymbol type, string wire, int depth)
    {
        if (CanonicalTypeRenderer.TryUnwrapNullable(type, out ITypeSymbol inner) && NeedsReader(inner))
        {
            // A null container stays null rather than failing AsList; the engine calls this
            // delegate for every value it reads, null included.
            //
            // Both branches are cast explicitly, and that is load-bearing rather than tidy. A
            // bare `cond ? null : x` has no natural type when x is a value type, so it only
            // compiles where a target type exists — true at the top level, where the lambda
            // returns object?, and false in every nested position: a Select projection, a
            // ToDictionary selector, a tuple element. `List<(int, string)?>` is an ordinary
            // Python shape (`list[tuple[int, str] | None]`), and without the casts it emitted
            // code that failed in the consumer's build with a type-inference error pointing at
            // generated source. The reference-type branch needs the `?` too: casting null to a
            // non-nullable reference type is CS8600, which is an error under the
            // TreatWarningsAsErrors this repo and its consumers use.
            string nullable = FqNullable(type);
            return $"({wire} is null ? ({nullable})null : ({nullable}){ReadExpression(inner, wire, depth)})";
        }

        if (!NeedsReader(type))
        {
            return ElementExpression(type, wire);
        }

        string item = "item" + depth.ToString(CultureInfo.InvariantCulture);

        if (type is IArrayTypeSymbol array)
        {
            return $"global::System.Linq.Enumerable.ToArray({Projection(array.ElementType, wire, item, depth)})";
        }

        INamedTypeSymbol named = (INamedTypeSymbol)type;
        if (IsTuple(named))
        {
            return TupleExpression(named, wire, depth);
        }

        ITypeSymbol first = named.TypeArguments[0];
        return CanonicalTypeRenderer.FullName(named) switch
        {
            "System.Collections.Generic.List" =>
                $"global::System.Linq.Enumerable.ToList({Projection(first, wire, item, depth)})",
            "System.Collections.Generic.HashSet" =>
                $"new global::System.Collections.Generic.HashSet<{Fq(first)}>({Projection(first, wire, item, depth)})",
            "System.Collections.Frozen.FrozenSet" =>
                $"global::System.Collections.Frozen.FrozenSet.ToFrozenSet({Projection(first, wire, item, depth)})",
            "System.Collections.Immutable.ImmutableHashSet" =>
                "global::System.Collections.Immutable.ImmutableHashSet.CreateRange("
                    + $"{Projection(first, wire, item, depth)})",
            _ => MapExpression(named, wire, depth),
        };
    }

    private static string Projection(ITypeSymbol elementType, string wire, string item, int depth) =>
        "global::System.Linq.Enumerable.Select("
        + $"global::Versionable.Engine.WireValues.AsList({wire}), "
        + $"{item} => {ReadExpression(elementType, item, depth + 1)})";

    private static string MapExpression(INamedTypeSymbol named, string wire, int depth)
    {
        // Keys arrive as strings whatever they were declared as — the writer stringifies them —
        // so the declared key type is what turns them back, exactly as it does in Python.
        string entry = "entry" + depth.ToString(CultureInfo.InvariantCulture);

        return "global::System.Linq.Enumerable.ToDictionary("
            + $"global::Versionable.Engine.WireValues.AsMap({wire}), "
            + $"{entry} => {ReadExpression(named.TypeArguments[0], entry + ".Key", depth + 1)}, "
            + $"{entry} => {ReadExpression(named.TypeArguments[1], entry + ".Value", depth + 1)})";
    }

    private static string TupleExpression(INamedTypeSymbol named, string wire, int depth)
    {
        ImmutableArray<ITypeSymbol> elements = named.IsTupleType
            ? named.TupleElements.Select(element => element.Type).ToImmutableArray()
            : named.TypeArguments;

        string items = "items" + depth.ToString(CultureInfo.InvariantCulture);
        IEnumerable<string> reads = elements.Select((element, index) => ReadExpression(
            element,
            $"{items}[{index.ToString(CultureInfo.InvariantCulture)}]",
            depth + 1));

        // A one-element tuple has no tuple syntax — `(x)` is just a parenthesised expression —
        // so it has to be constructed by name. The switch is how a single expression gets a
        // local to index: one `var` arm is exhaustive, so nothing warns.
        string construction = elements.Length == 1
            ? $"new global::System.ValueTuple<{Fq(elements[0])}>({string.Join(", ", reads)})"
            : $"({string.Join(", ", reads)})";

        return $"(global::Versionable.Engine.WireValues.AsList({wire}) switch {{ var {items} => {construction} }})";
    }

    /// <summary>
    /// Hands one element back to the engine: the reflection-free path for a nested
    /// <c>[Versionable]</c> value, and the converter/enum/primitive path for everything else.
    /// </summary>
    /// <remarks>
    /// A <see langword="null"/> element is only rejected where the declared type cannot hold
    /// one <em>and</em> the failure would otherwise be unreadable. <c>WireValues.Read</c>
    /// returns null for a null wire value whatever the declared type — deliberately, since
    /// that is what Python's <c>deserialize</c> does — so a null inside a <c>List&lt;int&gt;</c>
    /// would reach an unboxing cast and surface as a bare <c>NullReferenceException</c> naming
    /// nothing. Rejecting it here, with the declared type in the message, is the difference
    /// between a diagnosable file and a stack trace.
    /// <para>
    /// Non-nullable <em>reference</em> elements are left alone on purpose. Null flows through
    /// them without crashing, and rejecting it would make C# stricter than the Python that
    /// wrote the file — a `list[str]` holding a null is a schema violation neither
    /// implementation currently polices, and making the C# side alone refuse it would fail
    /// loads that Python round-trips.
    /// </para>
    /// </remarks>
    private static string ElementExpression(ITypeSymbol type, string wire)
    {
        if (TryVersionableMetadata(type, out string metadata))
        {
            return $"({Fq(type)})global::Versionable.Engine.WireValues.ReadVersionable({wire}, {metadata})";
        }

        string read = $"global::Versionable.Engine.WireValues.Read({wire}, typeof({Fq(type)}))";

        if (type.IsValueType && !CanonicalTypeRenderer.TryUnwrapNullable(type, out _))
        {
            string message = SymbolDisplay.FormatLiteral(
                $"Expected a value of type '{Fq(type).Replace("global::", string.Empty)}' inside this container, "
                    + "but the file holds null.",
                quote: true);
            return $"({Fq(type)})({read} ?? throw new global::Versionable.Errors.ConverterException({message}))";
        }

        return $"({Fq(type)}){read}!";
    }

    /// <summary>
    /// Whether the element's own generated metadata can be named, which skips the registry
    /// lookup entirely.
    /// </summary>
    /// <remarks>
    /// Only when the member is certain to exist: a source type carrying <c>[Versionable]</c>
    /// that is <c>partial</c> all the way out (this generator will emit it), or a referenced
    /// type that already implements <c>IVersionableMetadataProvider</c>. A source type that is
    /// not partial gets no member — the analyzer reports VSN0005 — so naming it would turn one
    /// clear diagnostic into a wall of compiler errors.
    /// </remarks>
    private static bool TryVersionableMetadata(ITypeSymbol type, out string access)
    {
        access = string.Empty;

        if (type is not INamedTypeSymbol named
            || named.IsGenericType
            || SchemaModelBuilder.FindVersionableAttribute(named) is null)
        {
            return false;
        }

        bool reachable = named.DeclaringSyntaxReferences.Length == 0
            ? named.AllInterfaces.Any(contract =>
                CanonicalTypeRenderer.FullName(contract) == "Versionable.IVersionableMetadataProvider")
            : SchemaModelBuilder.IsPartialEverywhere(named);

        if (!reachable)
        {
            return false;
        }

        access = Fq(named) + ".VersionableMetadata";
        return true;
    }

    private static string Fq(ITypeSymbol type) => type.ToDisplayString(_clrTypeFormat);

    /// <summary>
    /// The nullable spelling of <paramref name="type"/>, for casting a conditional's branches.
    /// </summary>
    /// <remarks>
    /// A nullable value type already displays with its <c>?</c>; a nullable reference type does
    /// not, because the display format deliberately drops the annotation so that
    /// <c>typeof(...)</c> stays legal.
    /// </remarks>
    private static string FqNullable(ITypeSymbol type)
    {
        string text = Fq(type);
        return text.EndsWith("?", StringComparison.Ordinal) ? text : text + "?";
    }

    private static void RenderRegistration(Writer writer, SchemaModel model, string self, string hide)
    {
        // Nested rather than top-level so the emitted name can never collide across
        // assemblies, and PascalCase so the repo's naming rules hold in generated code too.
        writer.Line("/// <summary>Registers this type's metadata when the module loads.</summary>");
        writer.Line($"internal static {hide}class VersionableRegistration");
        writer.Open();
        writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        writer.Line("internal static void Initialize() =>");
        writer.Indent();

        // Register=false claims no Serialization Name but stays reachable by CLR type, which
        // is what keeps it serializable as a nested value (VersionableRegistry docs).
        string method = model.Register ? "Register" : "RegisterTypeOnly";
        writer.Line($"{Runtime}VersionableRegistry.{method}({self}.VersionableMetadata);");
        writer.Outdent();
        writer.Close();
    }

    private static string FactoryExpression(SchemaModel model, string self)
    {
        if (model.IsAbstract)
        {
            // A polymorphic base is never constructed: the value's own envelope names the
            // concrete type, and this metadata is only the upper bound that resolution checks
            // against. `new` on it would not compile, so the factory says why instead.
            return $"throw new global::Versionable.Errors.VersionableException(\"'{model.SerializationName}' is "
                + "abstract and is never constructed directly; a file names its concrete type in the envelope's "
                + "'object' key.\")";
        }

        FactoryPlan plan = model.Factory!;
        IEnumerable<string> arguments = plan.ParameterFields.Select(index =>
            $"({model.Fields[index].ClrType.ToDisplayString(_clrTypeFormat)})values[{index.ToString(CultureInfo.InvariantCulture)}]!");

        string construction = $"new {self}({string.Join(", ", arguments)})";
        if (plan.InitializerFields.Length == 0)
        {
            return construction;
        }

        IEnumerable<string> assignments = plan.InitializerFields.Select(index =>
            $"{model.Fields[index].ClrName} = "
            + $"({model.Fields[index].ClrType.ToDisplayString(_clrTypeFormat)})"
            + $"values[{index.ToString(CultureInfo.InvariantCulture)}]!");

        return construction + " { " + string.Join(", ", assignments) + " }";
    }

    private static string Declaration(INamedTypeSymbol type)
    {
        string accessibility = type.DeclaredAccessibility switch
        {
            Accessibility.Public => "public ",
            Accessibility.Internal => "internal ",
            Accessibility.Private => "private ",
            Accessibility.Protected => "protected ",
            Accessibility.ProtectedOrInternal => "protected internal ",
            Accessibility.ProtectedAndInternal => "private protected ",
            _ => string.Empty,
        };

        string keyword = type switch
        {
            { IsRecord: true, TypeKind: TypeKind.Struct } => "record struct",
            { IsRecord: true } => "record",
            { TypeKind: TypeKind.Struct } => "struct",
            _ => "class",
        };

        return $"{accessibility}partial {keyword} {type.Name}";
    }

    private static string CSharpLiteral(TypedConstant value)
    {
        if (value.IsNull)
        {
            return "null";
        }

        return value.Value switch
        {
            bool flag => flag ? "true" : "false",
            string text => SymbolDisplay.FormatLiteral(text, quote: true),
            int number => number.ToString(CultureInfo.InvariantCulture),
            long number => number.ToString(CultureInfo.InvariantCulture) + "L",
            sbyte or byte or short or ushort or uint or ulong =>
                $"({value.Type!.ToDisplayString(_clrTypeFormat)})"
                + Convert.ToString(value.Value, CultureInfo.InvariantCulture),
            _ => "null",
        };
    }

    private static string Quote(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Bool(bool value) => value ? "true" : "false";

    /// <summary>A minimal indenting source writer — enough for one generated file shape.</summary>
    private sealed class Writer
    {
        private readonly StringBuilder _text = new();
        private int _depth;

        internal void Line(string text = "")
        {
            if (text.Length > 0)
            {
                _text.Append(' ', _depth * 4);
                _text.Append(text);
            }

            _text.Append('\n');
        }

        internal void Open()
        {
            Line("{");
            _depth++;
        }

        internal void Close() => CloseWith("}");

        internal void CloseWith(string text)
        {
            _depth--;
            Line(text);
        }

        internal void Indent() => _depth++;

        internal void Outdent() => _depth--;

        public override string ToString() => _text.ToString();
    }
}
