using Microsoft.CodeAnalysis;

namespace Versionable.Analyzers;

/// <summary>
/// Emits per-type <c>VersionableMetadata</c>, typed field accessors, a constructor invoker,
/// and a <c>[ModuleInitializer]</c> registry registration for every <c>[Versionable]</c> type.
/// </summary>
/// <remarks>
/// Replaces Python's runtime reflection (<c>_resolveFields</c> /
/// <c>typing.get_type_hints</c> in <c>src/versionable/_base.py</c>) with compile-time
/// codegen, which is what keeps the runtime Native AOT and trimming safe (ADR-0003).
/// Stub: generation lands in task 2b.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class VersionableMetadataGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The metadata pipeline lands in task 2b. Until then this marker is the only output:
        // it stamps every compilation the generator actually ran in, so the scaffold can
        // prove the ADR-0003 pipeline is wired rather than merely referenced. An assembly
        // attribute rather than a type, so the same marker landing in two assemblies that
        // see each other's internals cannot collide (CS0433).
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource(
            "VersionableGeneratorMarker.g.cs",
            """
            // <auto-generated/>
            [assembly: System.Reflection.AssemblyMetadata("Versionable.Generator", "VersionableMetadataGenerator")]
            """));
    }
}
