using Versionable.Backends;
using Versionable.Backends.Toml;
using Versionable.Engine;
using Xunit;

namespace Versionable.Tests;

/// <summary>
/// <c>commentDefaults</c>: fields still holding what their schema declares are written as comment
/// lines, so a generated config documents every setting it does not impose.
/// </summary>
/// <remarks>
/// Python counterpart: <c>TestTomlCommentDefaults</c> in <c>tests/test_toml_backend.py</c>, and
/// <c>_emitWithCommentedDefaults</c> in <c>src/versionable/_toml_backend.py</c>.
/// <para>
/// The four fixtures below mirror the four shapes Python's suite covers, and the expected text in
/// each test was <em>generated by Python</em> and pasted here — see the assertions, which quote
/// whole blocks rather than probing for substrings. Byte-identity is not the claim (the envelope
/// hash differs, and blank comment lines are dropped); every comment line, its placement relative
/// to the section headers, and which lines stay live are.
/// </para>
/// </remarks>
[Collection(RegistryCollection.Name)]
public class TomlCommentDefaultsTests : IDisposable
{
    private readonly string _directory =
        Path.Combine(Path.GetTempPath(), $"versionable-toml-defaults-{Path.GetRandomFileName()}");

    public TomlCommentDefaultsTests()
    {
        GoldenSchemas.EnsureRegistered();
        foreach (VersionableMetadata metadata in TomlCommentSchemas.All)
        {
            VersionableRegistry.Register(metadata);
        }

        Directory.CreateDirectory(_directory);
    }

    public void Dispose()
    {
        Directory.Delete(_directory, recursive: true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// A field at its default becomes a comment line; one the caller set stays live, and the
    /// envelope is never touched.
    /// </summary>
    /// <remarks>
    /// Python writes exactly this for the same object (<c>hash</c> aside):
    /// <code>
    /// required = "r"
    /// # name = "anon"
    /// # port = 8080
    ///
    /// [__versionable__]
    /// object = "TomlSettings"
    /// version = 1
    /// hash = ""
    /// </code>
    /// </remarks>
    [Fact]
    public void a_field_at_its_default_is_commented_out_and_the_envelope_is_not()
    {
        string text = SaveWithComments(new TomlSettings("r"), "settings.toml");

        Assert.Equal(
            """
            required = "r"
            # name = "anon"
            # port = 8080

            [__versionable__]
            object = "TomlSettings"
            version = 1
            hash = "aaaaaa"

            """.ReplaceLineEndings("\n"),
            text);
    }

    /// <summary>Nothing is commented when nothing is at its default.</summary>
    [Fact]
    public void a_field_the_caller_set_is_written_live()
    {
        string text = SaveWithComments(new TomlSettings("r", "given", 9000), "settings.toml");

        Assert.Contains("name = \"given\"\nport = 9000\n", text, StringComparison.Ordinal);
        Assert.DoesNotContain("# name", text, StringComparison.Ordinal);
        Assert.DoesNotContain("# port", text, StringComparison.Ordinal);
    }

    /// <summary>The option changes what the file says, never what it means.</summary>
    [Fact]
    public void a_commented_file_loads_back_with_the_defaults_restored()
    {
        string path = Path.Combine(_directory, "settings.toml");
        VersionableFile.Save(new TomlSettings("r"), path, options: new BackendSaveOptions { CommentDefaults = true });

        TomlSettings loaded = VersionableFile.Load<TomlSettings>(path);

        Assert.Equal("r", loaded.Required);
        Assert.Equal("anon", loaded.Name);
        Assert.Equal(8080, loaded.Port);
    }

    /// <summary>
    /// Deleting the <c>#</c> from a commented line is a valid override — which is the entire point
    /// of writing the line.
    /// </summary>
    [Fact]
    public void uncommenting_a_default_line_overrides_it()
    {
        string path = Path.Combine(_directory, "settings.toml");
        VersionableFile.Save(new TomlSettings("r"), path, options: new BackendSaveOptions { CommentDefaults = true });

        File.WriteAllText(path, File.ReadAllText(path).Replace("# port = 8080", "port = 9999", StringComparison.Ordinal));

        Assert.Equal(9999, VersionableFile.Load<TomlSettings>(path).Port);
    }

    /// <summary>
    /// A nested object left at its default is commented whole — header, keys, and envelope
    /// sub-table.
    /// </summary>
    /// <remarks>
    /// <b>A deliberate divergence from Python</b>, shared with the YAML backend and recorded on
    /// <see cref="BackendSaveOptions.CommentDefaults"/>. Python leaves <c>[db]</c> and
    /// <c>[db.__versionable__]</c> live and comments only the two keys, which writes an envelope
    /// for an object the file does not set: reload it and <c>db</c> is an empty table claiming to
    /// be a <c>TomlHost</c>, refilled from the default only because every one of its fields
    /// happens to have one. Commenting the block out is what "this field is not set" already means
    /// for every other field, and it is what
    /// <see cref="YamlTomlCommentDefaultsTests"/> pins across the two backends.
    /// <para>
    /// The block sits with the other sections, after the envelope, rather than inline where the
    /// field is declared — see
    /// <see cref="a_commented_section_never_precedes_a_live_key_line"/> for why that placement is
    /// load-bearing rather than cosmetic.
    /// </para>
    /// </remarks>
    [Fact]
    public void a_nested_object_at_its_default_is_commented_out_whole()
    {
        string text = SaveWithComments(new TomlHostRoot("x"), "nested.toml");

        Assert.Equal(
            """
            label = "x"

            [__versionable__]
            object = "TomlHostRoot"
            version = 1
            hash = "aaaaaa"

            # [db]
            # host = "localhost"
            # port = 5432
            # [db.__versionable__]
            # object = "TomlHost"
            # version = 1
            # hash = "aaaaaa"

            """.ReplaceLineEndings("\n"),
            text);

        // Nothing from the block is live, and the field still comes back from its default factory.
        foreach (string line in text.Split('\n'))
        {
            Assert.False(line.StartsWith("[db", StringComparison.Ordinal), line);
        }

        Assert.Equal("localhost", VersionableFile.Load<TomlHostRoot>(Path.Combine(_directory, "nested.toml")).Db.Host);
    }

    /// <summary>
    /// A nested object the caller <em>did</em> set keeps its section, and the defaults still
    /// standing inside it are commented there.
    /// </summary>
    /// <remarks>
    /// The other half of the rule above, and the one place this backend still goes further than
    /// the YAML one: TOML's sections are addressable, so a live section's own fields can be
    /// compared against the nested type's defaults and commented in place. YAML comments top-level
    /// fields only. Both are recorded on <see cref="BackendSaveOptions.CommentDefaults"/>.
    /// </remarks>
    [Fact]
    public void defaults_inside_a_live_nested_section_are_commented_in_place()
    {
        string text = SaveWithComments(new TomlHostRoot("x", new TomlHost("db.internal")), "live-nested.toml");

        Assert.Equal(
            """
            label = "x"

            [__versionable__]
            object = "TomlHostRoot"
            version = 1
            hash = "aaaaaa"

            [db]
            host = "db.internal"
            # port = 5432

            [db.__versionable__]
            object = "TomlHost"
            version = 1
            hash = "aaaaaa"

            """.ReplaceLineEndings("\n"),
            text);

        TomlHostRoot loaded = VersionableFile.Load<TomlHostRoot>(Path.Combine(_directory, "live-nested.toml"));
        Assert.Equal("db.internal", loaded.Db.Host);
        Assert.Equal(5432, loaded.Db.Port);
    }

    /// <summary>
    /// A default that renders as several lines has every one of them commented, headers included.
    /// </summary>
    /// <remarks>
    /// Python writes the same block (with an extra bare <c>#</c> where a blank line fell). This is
    /// the case a naive implementation gets wrong: comment only the <c>[[items]]</c> header and
    /// the <c>a = 1</c> under it becomes a live key of whatever table precedes it.
    /// </remarks>
    [Fact]
    public void a_multi_line_default_is_commented_on_every_line()
    {
        string text = SaveWithComments(new TomlListRoot("x"), "list.toml");

        Assert.Equal(
            """
            label = "x"

            [__versionable__]
            object = "TomlListRoot"
            version = 1
            hash = "aaaaaa"

            # [[items]]
            # a = 1
            # [items.__versionable__]
            # object = "TomlListItem"
            # version = 1
            # hash = "aaaaaa"

            """.ReplaceLineEndings("\n"),
            text);

        // Nothing from the block is live: a stray uncommented header or key would reappear here.
        foreach (string line in text.Split('\n'))
        {
            Assert.False(line.StartsWith("[[items]]", StringComparison.Ordinal), line);
            Assert.False(line.StartsWith("[items.", StringComparison.Ordinal), line);
        }

        // The commented block is not a key, so the list comes back from the default factory.
        TomlListItem item = Assert.Single(VersionableFile.Load<TomlListRoot>(Path.Combine(_directory, "list.toml")).Items);
        Assert.Equal(1, item.A);
    }

    /// <summary>
    /// A multi-line default one level down carries the full dotted path in its header, so
    /// uncommenting it writes to the field it came from.
    /// </summary>
    /// <remarks>
    /// <b>A deliberate improvement on Python</b>, recorded on
    /// <see cref="BackendSaveOptions.CommentDefaults"/>: Python renders the default block in
    /// isolation with <c>tomlkit</c> and so emits a root-relative <c>[[items]]</c> here, which a
    /// reader who deletes the <c>#</c> would find lands in a root field of that name — a different
    /// field, or none at all. The header written here is <c>[[inner.items]]</c>, and the assertion
    /// below is what says it: the uncommented block reaches <c>Inner.Items</c>, not the root.
    /// </remarks>
    [Fact]
    public void a_multi_line_default_one_level_down_is_commented_with_its_full_path()
    {
        string text = SaveWithComments(new TomlOuterRoot("outer", new TomlListRoot("y")), "outer.toml");

        Assert.Equal(
            """
            label = "outer"

            [__versionable__]
            object = "TomlOuterRoot"
            version = 1
            hash = "aaaaaa"

            [inner]
            label = "y"

            [inner.__versionable__]
            object = "TomlListRoot"
            version = 1
            hash = "aaaaaa"

            # [[inner.items]]
            # a = 1
            # [inner.items.__versionable__]
            # object = "TomlListItem"
            # version = 1
            # hash = "aaaaaa"

            """.ReplaceLineEndings("\n"),
            text);

        // Delete the `#` from the block and change the value: a root-relative header would put the
        // 7 in a root `items` the outer type does not declare, and Inner.Items would come back as
        // the default 1.
        string path = Path.Combine(_directory, "outer.toml");
        File.WriteAllText(
            path,
            text.Replace("# ", string.Empty, StringComparison.Ordinal)
                .Replace("a = 1", "a = 7", StringComparison.Ordinal));

        Assert.Equal(7, Assert.Single(VersionableFile.Load<TomlOuterRoot>(path).Inner.Items).A);
    }

    /// <summary>
    /// A commented section never precedes a live <c>key = value</c> line, whatever order the
    /// fields are declared in.
    /// </summary>
    /// <remarks>
    /// <b>The reason commented sections are emitted with the sections rather than inline.</b> TOML
    /// binds a bare key to the most recent table header, and a commented block is only worth
    /// writing if deleting the <c>#</c> leaves a file that means what it says. Emit
    /// <c># [db] … # [db.__versionable__] …</c> and then <c>name = "prod"</c>, and the moment a
    /// reader uncomments the block that <c>name</c> becomes a key of <c>[db.__versionable__]</c> —
    /// an unknown envelope key, dropped without complaint, so the field silently reverts to
    /// <c>"anon"</c>. Nothing about the file as written looks wrong; the loss only appears after
    /// the edit the comment exists to invite.
    /// <para>
    /// The YAML backend cannot reach this shape — its comments are indentation-scoped, so a
    /// commented block is positionally inert — which is why the fix is TOML's alone and why
    /// <see cref="YamlTomlCommentDefaultsTests"/> asserts the outcome rather than the layout.
    /// </para>
    /// </remarks>
    [Fact]
    public void a_commented_section_never_precedes_a_live_key_line()
    {
        // `db` is declared first and left at its default; `name` is declared after it and set.
        string text = SaveWithComments(new TomlOrderRoot(name: "prod"), "order.toml");

        Assert.Equal(
            """
            name = "prod"

            [__versionable__]
            object = "TomlOrderRoot"
            version = 1
            hash = "aaaaaa"

            # [db]
            # host = "localhost"
            # port = 5432
            # [db.__versionable__]
            # object = "TomlHost"
            # version = 1
            # hash = "aaaaaa"

            """.ReplaceLineEndings("\n"),
            text);

        string[] lines = text.ReplaceLineEndings("\n").Split('\n');
        Assert.True(
            Array.FindIndex(lines, line => line.StartsWith("name = ", StringComparison.Ordinal))
                < Array.FindIndex(lines, line => line.StartsWith("# [", StringComparison.Ordinal)),
            text);

        // The edit the comment invites: delete every `#` and the file still says name = "prod".
        string path = Path.Combine(_directory, "order.toml");
        File.WriteAllText(path, text.Replace("# ", string.Empty, StringComparison.Ordinal));

        TomlOrderRoot loaded = VersionableFile.Load<TomlOrderRoot>(path);
        Assert.Equal("prod", loaded.Name);
        Assert.Equal("localhost", loaded.Db.Host);
    }

    /// <summary>Without the option the same object writes every field live.</summary>
    [Fact]
    public void the_option_is_off_by_default()
    {
        string path = Path.Combine(_directory, "settings.toml");
        VersionableFile.Save(new TomlSettings("r"), path);

        string text = File.ReadAllText(path);
        Assert.DoesNotContain("#", text, StringComparison.Ordinal);
        Assert.Contains("name = \"anon\"", text, StringComparison.Ordinal);
    }

    /// <summary>
    /// The other backends ignore the option rather than failing on it, as Python's do.
    /// </summary>
    [Fact]
    public void a_backend_without_comments_ignores_the_option()
    {
        string path = Path.Combine(_directory, "settings.json");

        VersionableFile.Save(new TomlSettings("r"), path, options: new BackendSaveOptions { CommentDefaults = true });

        Assert.Equal("anon", VersionableFile.Load<TomlSettings>(path).Name);
    }

    private string SaveWithComments(object value, string file)
    {
        string path = Path.Combine(_directory, file);
        VersionableFile.Save(value, path, options: new BackendSaveOptions { CommentDefaults = true });
        return File.ReadAllText(path);
    }
}

/// <summary>
/// Registration list for the four schemas the <c>commentDefaults</c> tests write.
/// </summary>
/// <remarks>
/// Hand-written metadata, as <c>EngineTestSchemas.cs</c> uses: these types exist to mirror the
/// Python dataclasses in <c>tests/test_toml_backend.py</c> field for field and default for
/// default, and nothing about them needs the generator.
/// </remarks>
internal static class TomlCommentSchemas
{
    /// <summary>Every schema these tests register.</summary>
    internal static IReadOnlyList<VersionableMetadata> All { get; } =
    [
        TomlSettings.Metadata,
        TomlHost.Metadata,
        TomlHostRoot.Metadata,
        TomlListItem.Metadata,
        TomlListRoot.Metadata,
        TomlOuterRoot.Metadata,
        TomlOrderRoot.Metadata,
    ];
}

/// <summary>Two defaulted fields after one required field. Python: <c>TomlSettings</c>.</summary>
internal sealed class TomlSettings(string required, string name = "anon", int port = 8080)
    : IVersionableMetadataProvider
{
    /// <summary>A field with no default, which a file must supply.</summary>
    public string Required { get; } = required;

    /// <summary>A defaulted string.</summary>
    public string Name { get; } = name;

    /// <summary>A defaulted integer.</summary>
    public int Port { get; } = port;

    /// <summary>Metadata, as the generator would emit it.</summary>
    public static VersionableMetadata Metadata { get; } = new()
    {
        ClrType = typeof(TomlSettings),
        Name = "TomlSettings",
        Version = 1,
        Hash = "aaaaaa",
        Fields =
        [
            TestMetadata.Field<TomlSettings>(
                "required", "Required", typeof(string), "str", settings => settings.Required),
            TestMetadata.Field<TomlSettings>(
                "name", "Name", typeof(string), "str", settings => settings.Name, () => "anon"),
            TestMetadata.Field<TomlSettings>(
                "port", "Port", typeof(int), "int", settings => settings.Port, () => 8080),
        ],
        Factory = values => new TomlSettings((string)values[0]!, (string)values[1]!, (int)values[2]!),
    };

    static VersionableMetadata IVersionableMetadataProvider.VersionableMetadata => Metadata;
}

/// <summary>A nested object whose every field has a default. Python: <c>TomlHost</c>.</summary>
internal sealed class TomlHost(string host = "localhost", int port = 5432) : IVersionableMetadataProvider
{
    /// <summary>A defaulted string.</summary>
    public string Host { get; } = host;

    /// <summary>A defaulted integer.</summary>
    public int Port { get; } = port;

    /// <summary>Metadata, as the generator would emit it.</summary>
    public static VersionableMetadata Metadata { get; } = new()
    {
        ClrType = typeof(TomlHost),
        Name = "TomlHost",
        Version = 1,
        Hash = "aaaaaa",
        Fields =
        [
            TestMetadata.Field<TomlHost>("host", "Host", typeof(string), "str", host => host.Host, () => "localhost"),
            TestMetadata.Field<TomlHost>("port", "Port", typeof(int), "int", host => host.Port, () => 5432),
        ],
        Factory = values => new TomlHost((string)values[0]!, (int)values[1]!),
    };

    static VersionableMetadata IVersionableMetadataProvider.VersionableMetadata => Metadata;
}

/// <summary>Holds a <see cref="TomlHost"/> defaulted to a fresh one. Python: <c>TomlHostRoot</c>.</summary>
internal sealed class TomlHostRoot(string label, TomlHost? db = null) : IVersionableMetadataProvider
{
    /// <summary>A required label.</summary>
    public string Label { get; } = label;

    /// <summary>The nested object, defaulted.</summary>
    public TomlHost Db { get; } = db ?? new TomlHost();

    /// <summary>Metadata, as the generator would emit it.</summary>
    public static VersionableMetadata Metadata { get; } = new()
    {
        ClrType = typeof(TomlHostRoot),
        Name = "TomlHostRoot",
        Version = 1,
        Hash = "aaaaaa",
        Fields =
        [
            TestMetadata.Field<TomlHostRoot>("label", "Label", typeof(string), "str", root => root.Label),
            TestMetadata.Field<TomlHostRoot>(
                "db",
                "Db",
                typeof(TomlHost),
                "TomlHost",
                root => root.Db,
                () => new TomlHost(),
                wire => WireValues.ReadVersionable(wire, TomlHost.Metadata)),
        ],
        Factory = values => new TomlHostRoot((string)values[0]!, (TomlHost)values[1]!),
    };

    static VersionableMetadata IVersionableMetadataProvider.VersionableMetadata => Metadata;
}

/// <summary>The element of the list-default fixture. Python: <c>TomlListItem</c>.</summary>
internal sealed class TomlListItem(int a = 1) : IVersionableMetadataProvider
{
    /// <summary>A defaulted integer.</summary>
    public int A { get; } = a;

    /// <summary>Metadata, as the generator would emit it.</summary>
    public static VersionableMetadata Metadata { get; } = new()
    {
        ClrType = typeof(TomlListItem),
        Name = "TomlListItem",
        Version = 1,
        Hash = "aaaaaa",
        Fields = [TestMetadata.Field<TomlListItem>("a", "A", typeof(int), "int", item => item.A, () => 1)],
        Factory = values => new TomlListItem((int)values[0]!),
    };

    static VersionableMetadata IVersionableMetadataProvider.VersionableMetadata => Metadata;
}

/// <summary>
/// Holds a list defaulted to one element, which is the multi-line default case. Python:
/// <c>TomlListRoot</c>.
/// </summary>
internal sealed class TomlListRoot(string label, List<TomlListItem>? items = null) : IVersionableMetadataProvider
{
    /// <summary>A required label.</summary>
    public string Label { get; } = label;

    /// <summary>The list, defaulted to a single default element.</summary>
    public List<TomlListItem> Items { get; } = items ?? [new TomlListItem()];

    /// <summary>Metadata, as the generator would emit it.</summary>
    public static VersionableMetadata Metadata { get; } = new()
    {
        ClrType = typeof(TomlListRoot),
        Name = "TomlListRoot",
        Version = 1,
        Hash = "aaaaaa",
        Fields =
        [
            TestMetadata.Field<TomlListRoot>("label", "Label", typeof(string), "str", root => root.Label),
            TestMetadata.Field<TomlListRoot>(
                "items",
                "Items",
                typeof(List<TomlListItem>),
                "list[TomlListItem]",
                root => root.Items,
                () => new List<TomlListItem> { new() },
                wire => TestMetadata.ReadList(
                    wire, item => (TomlListItem)WireValues.ReadVersionable(item, TomlListItem.Metadata))),
        ],
        Factory = values => new TomlListRoot((string)values[0]!, (List<TomlListItem>)values[1]!),
    };

    static VersionableMetadata IVersionableMetadataProvider.VersionableMetadata => Metadata;
}

/// <summary>
/// A defaulted nested object declared <em>before</em> a defaulted scalar: the field order that
/// makes a commented section's placement a correctness question rather than a cosmetic one.
/// </summary>
/// <remarks>
/// No Python counterpart. Its suite declares the nested object last in every commentDefaults
/// fixture, which is why an emitter that writes commented blocks inline passes there.
/// </remarks>
internal sealed class TomlOrderRoot(TomlHost? db = null, string name = "anon") : IVersionableMetadataProvider
{
    /// <summary>The nested object, defaulted and declared first.</summary>
    public TomlHost Db { get; } = db ?? new TomlHost();

    /// <summary>A defaulted scalar, declared after the nested object.</summary>
    public string Name { get; } = name;

    /// <summary>Metadata, as the generator would emit it.</summary>
    public static VersionableMetadata Metadata { get; } = new()
    {
        ClrType = typeof(TomlOrderRoot),
        Name = "TomlOrderRoot",
        Version = 1,
        Hash = "aaaaaa",
        Fields =
        [
            TestMetadata.Field<TomlOrderRoot>(
                "db",
                "Db",
                typeof(TomlHost),
                "TomlHost",
                root => root.Db,
                () => new TomlHost(),
                wire => WireValues.ReadVersionable(wire, TomlHost.Metadata)),
            TestMetadata.Field<TomlOrderRoot>(
                "name", "Name", typeof(string), "str", root => root.Name, () => "anon"),
        ],
        Factory = values => new TomlOrderRoot((TomlHost)values[0]!, (string)values[1]!),
    };

    static VersionableMetadata IVersionableMetadataProvider.VersionableMetadata => Metadata;
}

/// <summary>
/// Holds a <see cref="TomlListRoot"/> with no default of its own, which is what puts a multi-line
/// default one level down from the root.
/// </summary>
/// <remarks>
/// No Python counterpart: its suite has no fixture that nests a list default, which is exactly why
/// the root-relative header its emitter writes was never noticed there.
/// </remarks>
internal sealed class TomlOuterRoot(string label, TomlListRoot inner) : IVersionableMetadataProvider
{
    /// <summary>A required label.</summary>
    public string Label { get; } = label;

    /// <summary>The nested object, required so that its own section stays live.</summary>
    public TomlListRoot Inner { get; } = inner;

    /// <summary>Metadata, as the generator would emit it.</summary>
    public static VersionableMetadata Metadata { get; } = new()
    {
        ClrType = typeof(TomlOuterRoot),
        Name = "TomlOuterRoot",
        Version = 1,
        Hash = "aaaaaa",
        Fields =
        [
            TestMetadata.Field<TomlOuterRoot>("label", "Label", typeof(string), "str", root => root.Label),
            TestMetadata.Field<TomlOuterRoot>(
                "inner",
                "Inner",
                typeof(TomlListRoot),
                "TomlListRoot",
                root => root.Inner,
                wireReader: wire => WireValues.ReadVersionable(wire, TomlListRoot.Metadata)),
        ],
        Factory = values => new TomlOuterRoot((string)values[0]!, (TomlListRoot)values[1]!),
    };

    static VersionableMetadata IVersionableMetadataProvider.VersionableMetadata => Metadata;
}
